version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 253490770873.dkr.ecr.us-east-2.amazonaws.com
      - REPO_NAME=internship/test
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=${IMAGE_TAG}

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - echo Tagging the Docker image...
      - docker tag $REPO_NAME:$IMAGE_TAG 253490770873.dkr.ecr.us-east-2.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo Build phase complete.

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 253490770873.dkr.ecr.us-east-2.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: yes


